#+STARTUP: showall
#+TITLE: Notes about Better Living Through Criticism

*Introduction*

Oscar Wilde quote about criticism that prompted me back to my memories: I read
that essay, it made me think about criticism and /how to approach art/
(literature, music and cinema).


*What is criticism?*
Laying the grounds, examples, motifs. Explaining an abstract sensation, grasping
what lies beyond personal taste.


*Thoughts on aesthetic judgement (Kant and Burke)*

Notions are hard for me because of my background, but /challenging/. Written in a
way I can understand, reasoning about what they mean today and how we can relate
to them today.


*Reaction to a work of art*

How we react and why. What moves to seek out a work of art. How the work of art
/changes/ us (i.e. Rainer Maria Rilke). Perceptions, feelings. Philip Larkin and
art as both a solitary and universal experience. Conveying something for which
words are not easy to find.


*Self-criticism*

Questioning his own position as critic, his own recollection of experiences as
steps onto the path of criticism. Ethic? Narrowing it down to a comfort zone or
broadening his own boundaries because of his privilege?


*What to make of Art?*

Museum and what it leaves us: what can we do with the art it contains? We take
for granted the masterpieces, accept their qualities or question them and the
authority (the government, the museum?) which is imposing them?


*Lost in the museum*

Today taste is globalized, we are consumers. However, there are cultural
hierarchies. A democratic taste is an illusion: only the privileged can access
to everything. Abounds of products: we are instrument of pure perception.


*Why critics exist?*

The case of John Keats: legend attributes his death to bad reviews. Critics are
useless, criticism can be dangerous. Art must take for what it is,
interpretation is ecocide (Susan Sontag). Is criticism a job? Do we need criticism?


*How to be wrong*

Tension between authorative and populist critic is intrinsic to criticism
itself. Critic must find its own voice, a voice you can trust. Critis has the
moral duty to be wrong. Solutionism (Evgeny Morozov). We live in the present,
trapped: we cannot be always on point because of time. We rever the past as we
try to predict the future. /To err is criticism/.


*The critical condition*

Is too much criticism good for criticism itself? Would it be better if there
were less voices out there? Criticism must adapt to the digital age. Check:
Samuel Johnson, George Gissing, Edmund Wilson, Yvor Winters.
