title: Films in Words
author: Manuel Uberti
email: manuel.uberti@inventati.org
description: > # this means to ignore newlines until "show_exerpts:"
  A corner of the web about films and cinephilia.
baseurl: ""
url: "https://www.filmsinwords.eu"
show_excerpts: true
excerpt_separator: <!--more-->

github_username: manuel-uberti
rss: rss

# Pagination
paginate: 5
paginate_path: "/page-:num/"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: manuel-uberti
    rss: rss

# Build settings
theme: minima

plugins:
 - jekyll-paginate
 - jekyll-feed
 - jekyll-seo-tag
