#+STARTUP: showall
#+TITLE: The special effect of Tsui Hark

It took me a while to understand and finally appreciate Tsui Hark’s output
since 2010. Up until 2008’s /All About Women/ I had always come to grips with
his cinema, in one way or another. However, I still remember leaving the
screening of /Detective Dee and the Mystery of the Phantom Flame/ at Venice Film
Festival with more concerns for his career than excitement for what I had just
seen. Somehow I wasn’t able to buy his love for CGI and 3-D.

Hindsight wisely taught me I was blatantly wrong. Tsui has always been
fascinated by special effects. Just think about both /Zu Warriors from the Magic
Mountain/ and /The Legend of Zu/. And what is /Green Snake/ if not his overtly
personal exploration of the White Snake folk tale by means of graphic aids?

Tsui Hark loves his visuals. He loves portraying stories and characters with
vibrant images and careful design. No wonder CGI has always interested him. It
enables him to stretch his skills further and devise new styles.

Admittedly, his first takes on 3-D weren’t enough for him to convince me he was
on the right path. /The Flying Swords of Dragon Gate/ felt like an endless trick
and /Young Detective Dee: Rise of the Sea Dragon/ just didn’t work. Then came
/The Taking of Tiger Mountain/ which showed Tsui was still capable behind the
camera despite 3-D moves of little interest to my eyes.

It’s only with /Sword Master/ and /Journey to the West: The Demons Strike Back/
that Tsui eventually unveils his unequivocal mastery of visual effects. /Sword
Master/ looks like a series of paintings where charming wuxia plots
unfold. Derek Yee is supposed to be the director, but it is clearly a Tsui Hark
work with his themes, his penchant for swords and blades and those villains that
reminded me of /Seven Swords/ at every fight.

The second chapter of Stephen Chow’s own retelling of /Journey to the West/ goes
so far and above Chow’s first effort in terms of visual exaggeration that it is
impossible to describe. Tsui transforms the regular Chinese blockbuster in an
avant-garde fantasy where aesthetic drives the action.

Stephen Chow has always avoid CGI as a tool for mimicking realism. Tsui embraces
this philosophy and lets the special effects build a vivid world out of the
fervid pages of the Chinese classic text.

It’s hard to tell what Tsui Hark next move is going to be. He trespassed and
reinvented the limits of cinema times and times again in his long career. He is
cinema’s most special effect.
