#+BLOG: filmsinwords
#+POSTID: 49
#+DATE: [2015-10-28 Wed 16:45]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Festival Alto Vicentino, Jury
#+TAGS:
#+DESCRIPTION:
#+TITLE: Street jury

Before ending up in charge of [[http://www.festivalaltovicentino.it/][Festival Alto Vicentino]], I started off as a member
of its jury back in 2012. It was my first experience in a Festival jury, and I
was happy to be there to decide which short films would have been the winners.

I was the only member of the jury without an academic curriculum devoted to
cinema, relying just on my indestructible albeit amateurish passion.

One thing I noticed back then was the poor attention editing and cinematography
were getting. The jury discussed the best shorts caring little about 2 of the
most important aspects I pay attention to when watching a film.

The same happened in 2013. I was not in the jury then, because I had gone
straight to the other side and had become an active player in the Festival Alto
Vicentino staff. I watched the new jury discuss the short films and again they
dismissed editing and cinematography. The jury assigned the respective prizes by
means of elimination.

2014 was the year that marked my first experience as festival director. Among
the assignments, I had to look for eligible candidates for the new
jury. Festival Alto Vicentino had been keeping the same head juror in the past
years, and that was the first thing I wanted to change.

I ended up with an almost totally renewed jury. This time I could not be there
to see how the jury would have assigned the prizes. However, only 2 out of 6
members showed up during the Festival closing night last summer. Weird,
especially because every single one of them lives not too far from Santorso.

That was it. Once again, I needed to rethink the jury.

For the next Festival Alto Vicentino (June, 2016), we will have a jury of 6
people. 3 men, 3 women. 3 out of 6 will have to conquer their place in the jury
by passing a test.

On 7th, 14th and 28th of November we will run a small contest. We will show some
of our shorts and the candidates will have to pick their favourite. They will
have to explain their choice and we will select our 3 jurors depending on how
convincing their explanations will be.

This process feels like bringing the jury selection back to the street. The
contest is open to everybody, because I don’t want the jury to be an elitist
group again. I also don’t care about any academic curricula whatsoever. I want
everyone to be able to express herself and her passion in the way that suits her
best. I want the candidates ready to convery their passion as freely as
possible.

As for the other 3 jurors, I am still working on it.
